remote_theme: christianezeani/panthera-jekyll
title: Brown Bread and Roses
subtitle: Bits and Pieces
description: Vaguely related to InfoSec

# Side Menu Links
menu:
  - text: GDPR
    link: /gdpr
    icon: ""
